//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bykova41p_Pr6
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_Clothes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Table_Clothes()
        {
            this.Table_Meaning = new HashSet<Table_Meaning>();
            this.Table_Purchase = new HashSet<Table_Purchase>();
        }
    
        public int IdClothes { get; set; }
        public string NameClothes { get; set; }
        public decimal PriceClothes { get; set; }
        public string ImageClothes { get; set; }
        public int IdGenderClothes { get; set; }
        public int IdMeaningClothes { get; set; }
    
        public virtual Table_Gender Table_Gender { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Table_Meaning> Table_Meaning { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Table_Purchase> Table_Purchase { get; set; }
    }
}
