//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bykova41p_Pr6
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_Phot
    {
        public int idPhot { get; set; }
        public int idUser { get; set; }
        public string path { get; set; }
        public byte[] Binpath { get; set; }
    
        public virtual Table_Users Table_Users { get; set; }
    }
}
